[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "caa352c37d09122f19345769ba5e4d3399e1d93a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "25a8c15158ae683fc3fdefa7d75d0c51759612aee2e9896a6c73ecd0f7f486a4"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.5+0/ABINIT.v9.10.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "68ea5c3db1148fbe10dbc0145ae52404e96047c3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "62d333892bd45e998b2fe85e25f55b9806ed0723abb13c72b44f865041f48181"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.5+0/ABINIT.v9.10.5.x86_64-linux-gnu-libgfortran5.tar.gz"
