[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "7abca26cdef817550c7f281ac6bf919fac07a16f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "e4879bc068a266b4a16929c956eb05370459f07cb1495dc8b514b04a8c3c7cb6"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.3+0/ABINIT.v9.10.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "16165d7963b67c58740311ef4fa9144afa6d606c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "99fc58daf9082b244d2e3dd6dc9e8be053f5eb2648490f72c8da09ff2247ef5f"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.3+0/ABINIT.v9.10.3.x86_64-linux-gnu-libgfortran5.tar.gz"
