[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "3e53b9e0b6db6da66859574bca9473fccbe489f6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "74902fed494354d419a0786179b6f0b31fcfe13058f08422a869c3c67a8d80e0"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.3+2/ABINIT.v9.10.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ABINIT]]
arch = "x86_64"
git-tree-sha1 = "379201cb0882f240c5f014e160053c5255d05881"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ABINIT.download]]
    sha256 = "c95c65ad97302869a7417bf994d899d7ff120af578cc6fa02cb059f6203ae56e"
    url = "https://github.com/epolack/ABINIT_jll.jl/releases/download/ABINIT-v9.10.3+2/ABINIT.v9.10.3.x86_64-linux-gnu-libgfortran5.tar.gz"
