# Autogenerated wrapper script for ABINIT_jll for x86_64-linux-gnu-libgfortran4
export abinit, abitk, aim, anaddb, atdep, band2eps, conducti, cut3d, dummy_tests, fftprof, fold2Bloch, ioprof, lapackprof, macroave, mrgddb, mrgdv, mrggkk, mrgscr, multibinit, optic, testtransposer, vdw_kernelgen

using FFTW_jll
using HDF5_jll
using LAPACK_jll
using Libxc_jll
using NetCDFF_jll
using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("ABINIT")
JLLWrappers.@declare_executable_product(abinit)
JLLWrappers.@declare_executable_product(abitk)
JLLWrappers.@declare_executable_product(aim)
JLLWrappers.@declare_executable_product(anaddb)
JLLWrappers.@declare_executable_product(atdep)
JLLWrappers.@declare_executable_product(band2eps)
JLLWrappers.@declare_executable_product(conducti)
JLLWrappers.@declare_executable_product(cut3d)
JLLWrappers.@declare_executable_product(dummy_tests)
JLLWrappers.@declare_executable_product(fftprof)
JLLWrappers.@declare_executable_product(fold2Bloch)
JLLWrappers.@declare_executable_product(ioprof)
JLLWrappers.@declare_executable_product(lapackprof)
JLLWrappers.@declare_executable_product(macroave)
JLLWrappers.@declare_executable_product(mrgddb)
JLLWrappers.@declare_executable_product(mrgdv)
JLLWrappers.@declare_executable_product(mrggkk)
JLLWrappers.@declare_executable_product(mrgscr)
JLLWrappers.@declare_executable_product(multibinit)
JLLWrappers.@declare_executable_product(optic)
JLLWrappers.@declare_executable_product(testtransposer)
JLLWrappers.@declare_executable_product(vdw_kernelgen)
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll, HDF5_jll, LAPACK_jll, Libxc_jll, NetCDFF_jll, CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_executable_product(
        abinit,
        "bin/abinit",
    )

    JLLWrappers.@init_executable_product(
        abitk,
        "bin/abitk",
    )

    JLLWrappers.@init_executable_product(
        aim,
        "bin/aim",
    )

    JLLWrappers.@init_executable_product(
        anaddb,
        "bin/anaddb",
    )

    JLLWrappers.@init_executable_product(
        atdep,
        "bin/atdep",
    )

    JLLWrappers.@init_executable_product(
        band2eps,
        "bin/band2eps",
    )

    JLLWrappers.@init_executable_product(
        conducti,
        "bin/conducti",
    )

    JLLWrappers.@init_executable_product(
        cut3d,
        "bin/cut3d",
    )

    JLLWrappers.@init_executable_product(
        dummy_tests,
        "bin/dummy_tests",
    )

    JLLWrappers.@init_executable_product(
        fftprof,
        "bin/fftprof",
    )

    JLLWrappers.@init_executable_product(
        fold2Bloch,
        "bin/fold2Bloch",
    )

    JLLWrappers.@init_executable_product(
        ioprof,
        "bin/ioprof",
    )

    JLLWrappers.@init_executable_product(
        lapackprof,
        "bin/lapackprof",
    )

    JLLWrappers.@init_executable_product(
        macroave,
        "bin/macroave",
    )

    JLLWrappers.@init_executable_product(
        mrgddb,
        "bin/mrgddb",
    )

    JLLWrappers.@init_executable_product(
        mrgdv,
        "bin/mrgdv",
    )

    JLLWrappers.@init_executable_product(
        mrggkk,
        "bin/mrggkk",
    )

    JLLWrappers.@init_executable_product(
        mrgscr,
        "bin/mrgscr",
    )

    JLLWrappers.@init_executable_product(
        multibinit,
        "bin/multibinit",
    )

    JLLWrappers.@init_executable_product(
        optic,
        "bin/optic",
    )

    JLLWrappers.@init_executable_product(
        testtransposer,
        "bin/testtransposer",
    )

    JLLWrappers.@init_executable_product(
        vdw_kernelgen,
        "bin/vdw_kernelgen",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
